from core.paths import APP_ROOT


OCR_WORK_DIR = APP_ROOT / "OCR_WORK"
DEFAULT_OCR_LANGUAGE = "eng+chi_tra+chi_sim"
DEFAULT_DPI = 300
DEFAULT_MIN_TEXT_LENGTH = 80
DEFAULT_MIN_DATE_COUNT = 1
DEFAULT_MIN_AMOUNT_COUNT = 2

